sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

  include:
    - php: 7.3
      env:
        - CHECK_CS=true
        - TEST_COVERAGE=true
    - php: 7.4
    - php: nightly

before_install:
  - if [[ $TEST_COVERAGE != 'true' && "$(php --version | grep xdebug -ci)" -ge 1 ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev --no-interaction --no-update php-coveralls/php-coveralls ; fi

script:
  - composer lint
  - composer stan
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry vendor/bin/php-coveralls -v ; fi
